jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run JavaScript script with secret
      run: node script.js
      env:
        # Map the GitHub secret to an environment variable name (e.g., NODE_API_KEY)
        PAT_TOKEN_KEY: ${{ secrets.PAT_TOKEN }} 
